import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import api from '../../services/api';

const empty = { title: '', subject: '', description: '', thumbnail_url: '' };
export const TrainerCourseFormPage = () => {
  const { courseId } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState(empty); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (courseId) api.get(`/trainer/courses/${courseId}`).then(r => setForm({ title: r.data.data.title || '', subject: r.data.data.subject || '', description: r.data.data.description || '', thumbnail_url: r.data.data.thumbnail_url || '' })).catch(e => setError(e.response?.data?.error || 'Could not load course.')); }, [courseId]);
  const submit = async e => { e.preventDefault(); setSaving(true); setError(''); try { const response = courseId ? await api.put(`/trainer/courses/${courseId}`, form) : await api.post('/trainer/courses', form); if (response.data.success) navigate('/trainer/courses'); } catch (e2) { setError(e2.response?.data?.error || 'Could not save course.'); } finally { setSaving(false); } };
  return <main className="container" style={{ maxWidth: 850, padding: '2rem 1rem' }}><Link to="/trainer/courses">← Course management</Link><h1>{courseId ? 'Edit course' : 'Create course draft'}</h1><p>Saving this form keeps the course in draft until you publish it.</p>{error && <div role="alert" className="badge badge-danger">{error}</div>}<form className="card" onSubmit={submit} style={{ padding: '1.25rem', display: 'grid', gap: '1rem' }}><label>Course title<input required maxLength="200" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Subject<input required maxLength="120" value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} /></label><label>Description<textarea rows="6" maxLength="10000" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><label>Thumbnail URL<input type="url" value={form.thumbnail_url} onChange={e => setForm({ ...form, thumbnail_url: e.target.value })} /></label>{form.thumbnail_url && <img src={form.thumbnail_url} alt="Course thumbnail preview" style={{ maxWidth: 320, maxHeight: 180, objectFit: 'cover' }} onError={e => { e.currentTarget.style.display = 'none'; }} />}<div style={{ display: 'flex', gap: '.5rem' }}><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving…' : 'Save draft'}</button><Link className="btn btn-secondary" to="/trainer/courses">Cancel</Link></div></form></main>;
};
